name: memotrip
description: "MEMOtrip — Smart Travel Planner & Memory Keeper with IoT Monitoring"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # UI & Design

  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Navigation & Maps
  url_launcher: ^6.3.1

  # Location & Weather
  geolocator: ^13.0.2
  http: ^1.2.2

  # Social Sharing
  share_plus: ^10.1.4

  # State Management
  flutter_riverpod: ^2.6.1
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  panorama_viewer: ^1.0.6
  image_picker: ^1.1.2
  firebase_storage: ^13.3.0
  image_picker_for_web: ^3.0.6
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
